apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-titanic
  labels:
    app: titanic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titanic
  template:
    metadata:
      labels:
        app: titanic
    spec:
      containers:
      - name: api-titanic
        image: jackobenco/application:v0.0.4
        ports:
        - containerPort: 8000
        env:
        - name: MLFLOW_TRACKING_URI
          value: "https://user-jackobenco016-mlflow.user.lab.sspcloud.fr"
        - name: MLFLOW_TRACKING_USERNAME
          value: user-jackobenco016
        - name: MLFLOW_TRACKING_PASSWORD
          value: ilaqgmqnvil9x7n1i754
        

          
